[package]
name = "times"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2.0.0"
chrono = "0.4.38"
anstyle = "1.0.7"
ecow = "0.2.5"
